### ISSUE TITLE
Request permissions when opening the app

### ISSUE THREAD

**Issue by cicciobellohalabua2** [edodson84/Aosp_Dialer_10_Gradle#14]
When opening the app, the app should ask the user for all permissions to function properly, eg "set phone app as default", "contacts permission", "show above other apps", "call log", " microphone ”,“ sms ”….
Currently you have to go into the settings and manually set it as the default phone and give all the various permissions

**Comment by edodson84** [comment]
Im in process of this. I have also updated app to androidx fragments still need to update preference fragments

**Comment by edodson84** [comment]
Added

**Comment by cicciobellohalabua2** [comment]
Thanks
